### ISSUE TITLE
What should we contribute ? 

### ISSUE THREAD

**Issue by droy117** [xtreme-coding/hacktoberfest-2022#16]
@xtreme-coding Hey I saw that this repo has hacktoberfest label on it but I don't know what to contribute. I only see some python codes. Can you please clarify? 
Thank You

**Comment by xtreme-coding** [comment]
You can solve coding problems from websites like geeksforgeeks, leetcode, codeforces, etc in your own language and contribute the solution here. Cheers!

**Comment by droy117** [comment]
Alright thanks

**Comment by slayeh17** [comment]
Confusion Cleared
